name: deepsky_protocol_v1
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
  # path: ^1.8.0

dependencies:
  deepsky_core:
    path: ../deepsky-core
  json5:
    git: git@github.com:ctsinc/json5-dart-fork.git

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
